
import { Button } from "@/components/ui/button";
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { AllComapreCharts } from "@/components/university/charts/AllCompareCharts";
import { AmountBasedChart } from "@/components/university/charts/AmountBasedChart";
import { FundChart } from "@/components/university/charts/FundChart";
import { PositionChart } from "@/components/university/charts/PositionChart";
import { FundAllList } from "@/components/university/fund/FundAllList";
import { DataTable } from "@/components/university/sidebar/data-table";
import { SectionCards } from "@/components/university/sidebar/section-cards";
import { UniversityJobList } from "@/components/university/UniversityJobList";
import { cn } from "@/lib/utils";
import { Check, ChevronsUpDown } from "lucide-react";
import React from "react";


const frameworks = [
  {
    value: "next.js",
    label: "Next.js",
  },
  {
    value: "sveltekit",
    label: "SvelteKit",
  },
  {
    value: "nuxt.js",
    label: "Nuxt.js",
  },
  {
    value: "remix",
    label: "Remix",
  },
  {
    value: "astro",
    label: "Astro",
  },
]

export default function UniversityHomePage() {
  const [open, setOpen] = React.useState(false)
  const [value, setValue] = React.useState("")
  return (
    <div className="@container/main flex flex-1 flex-col gap-2">
      <div className="flex flex-col gap-4 py-4">
        <SectionCards />        
          <div className="px-8 flex justify-between">
            <h1 className="text-2xl font-bold tracking-tight py-2">Report generated by year of 2025</h1>
            <div>
              <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-[200px] justify-between"
        >
          {value
            ? frameworks.find((framework) => framework.value === value)?.label
            : "Select year..."}
          <ChevronsUpDown className="opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[200px] p-0">
        <Command>
          <CommandInput placeholder="Search framework..." className="h-9" />
          <CommandList>
            <CommandEmpty>No framework found.</CommandEmpty>
            <CommandGroup>
              {frameworks.map((framework) => (
                <CommandItem
                  key={framework.value}
                  value={framework.value}
                  onSelect={(currentValue) => {
                    setValue(currentValue === value ? "" : currentValue)
                    setOpen(false)
                  }}
                >
                  {framework.label}
                  <Check
                    className={cn(
                      "ml-auto",
                      value === framework.value ? "opacity-100" : "opacity-0"
                    )}
                  />
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
            </div>
          </div>
        <div className="grid grid-cols-2 gap-6 px-6">
          <AllComapreCharts />
          <AmountBasedChart />
          <FundChart />
          <PositionChart />
        </div>
        {/* <DataTable data={data} /> */}
        <div>
          {/* <h1 className="px-8 text-2xl font-bold tracking-tight py-2 text-emerald-700">Job List</h1> */}
          <UniversityJobList />
          <div className="py-6">
          <FundAllList />
          </div>
        </div>
      </div>
    </div>
  )
}
